apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.image }}
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        env:
        - name: JAEGER_AGENT_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
{{ if .Values.configMap }}
        envFrom:
          - configMapRef:
               name: {{ .Values.service.name }}-configmap
{{ end }}
