apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:80
spec:
  rules:
  - host: {{ .Values.service.dns }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
